CREATE TABLE EMPLOYEE (
    EmployeeID NUMBER PRIMARY KEY,
    Name VARCHAR2(15),
    Salary NUMBER,
    Commission NUMBER,
    DeptID NUMBER
);
CREATE TABLE STUDENT (
    StudentID NUMBER PRIMARY KEY,
    Name VARCHAR2(15),
    Age NUMBER,
    City VARCHAR2(15)
);
CREATE TABLE DEPARTMENT (
    DeptID NUMBER PRIMARY KEY,
    DeptName VARCHAR2(15),
    Location VARCHAR2(15)
);

INSERT INTO EMPLOYEE VALUES(201, 'Ayesha', 35000, NULL, 20);
INSERT INTO EMPLOYEE VALUES(202, 'Hamza', 42000, 500, 30);
INSERT INTO EMPLOYEE VALUES(203, 'Ali', 30000, NULL, 20);

INSERT INTO STUDENT VALUES(24, 'Ali', 18, 'Karachi');
INSERT INTO STUDENT VALUES(25, 'Mariam', 19, 'Lahore');

INSERT INTO DEPARTMENT VALUES(10, 'HR', 'Karachi');
INSERT INTO DEPARTMENT VALUES(20, 'Finance', 'Islamabad');
INSERT INTO DEPARTMENT VALUES(30, 'IT', 'Lahore');

--INSERT
INSERT INTO STUDENT (StudentID, Name, Age, City)
VALUES (110, 'Fatima', 20, 'Lahore');
INSERT INTO EMPLOYEE (EmployeeID, Name, Salary, Commission, DeptID)
VALUES (501, 'Usman', 55000, NULL, 10);
 
--UPDATE
UPDATE STUDENT
SET City = 'Hyderabad'
WHERE StudentID = 25;

UPDATE EMPLOYEE
SET Salary = Salary + 5000
WHERE DeptID = 20
  AND Salary < 40000;
 
--DELETE
DELETE FROM STUDENT
WHERE Name = 'Ali'
  AND City = 'Karachi';

DELETE FROM EMPLOYEE
WHERE DeptID IN (
      SELECT DeptID
      FROM DEPARTMENT
      WHERE Location = 'Islamabad'
); 

SELECT * FROM EMPLOYEE;
SELECT * FROM STUDENT;
SELECT * FROM DEPARTMENT;
